export { default as logo } from './logo.png';
export { default as time } from './time.svg';
export { default as address } from './address.svg';
export { default as phone } from './phone.svg';
export { default as chevron } from './chevron.svg';
export { default as burger } from './burger.svg';
export { default as hero } from './hero.png';
export { default as actual1 } from './actual1.png';
export { default as info } from './info.png';